### ISSUE TITLE
Error Module is not defined

### ISSUE THREAD

**Issue by eugenee93** [shbatm/MMM-AlexaOnOff#1]
Hey, 

nice work with the code, but I got an error in the MMM-AlexaOnOff.js.
In line 11        Module.register("MMM-AlexaOnOff", {
the error "undefind variable for module" appears.

I'm pretty new to programming and Github, so sorry if this is a stupid question. 

Background of the problem: I installed your module MMM-AlexaOnOff for the MagicMirror and also the fauxmojes module, for turning the monitor  on/ off through Alexa.
The virtual Vemos device works but however no notification goes to the module. Going through the files in jshint the above mentioned error appears.

Many thanks in advance and I hope you could help me out. :)

Best regards, 
Eugen

**Comment by shbatm** [comment]
I can take a look, please post your config section for those two modules and the exact error you're getting in the log.

**Comment by eugenee93** [comment]
Hey, many thanks. Here are the sections for the two modules. 

**Magic Mirror config:**
```js
modules: [
		{
    			module: 'MMM-AlexaOnOff',
    			config: {
      		 		 devices: [{ 
             				 name: "Magic Mirror",
		
              			on: { 
                			notification: "MMM-AlexaOnOff_ACTION_RECEIVED",
                			payload: { actionName:'monitorOn' }
             				},
             			off: { 
                			notification: "MMM-AlexaOnOff_ACTION_RECEIVED",
                			payload: { actionName:'monitorOff' }
              				},
       				 }]
    			}
		},
```

**fauxmojs conifg:** (deleted the ip. adress for this message)
```js
`'use strict';

const FauxMo = require('fauxmojs');

let fauxMo = new FauxMo(
  {
    ipAddress: '',
    devices: [
  
      {
        name: 'Magic Mirror',
        port: 11001,
        handler: (action) => 
          console.log('Magic Mirror:', action);
        }
      }
    ]
  });

console.log('started..');
```

**Error in the log, when I start MMM-AlexaOnOff.js:**

```shell
/home/pi/MagicMirror/modules/MMM-AlexaOnOff/MMM-AlexaOnOff.js:11
Module.register("MMM-AlexaOnOff", {
^

ReferenceError: Module is not defined
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-AlexaOnOff/MMM-AlexaOnOff.js:11:1)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
```

As I mentioned before the fauxmojs config works and shows me my voice commands in the log, but it somehow don´t trigger the notifications in the MagicMirror config or MMM-AlexaOnOff config. 

If you need the whole files or something else just write me. 

Again, thank you very much for your help and have a nice Christmas.

Best regards, 
Eugen

**Comment by shbatm** [comment]
Are you by any chance trying to run just MMM-AlexaOnOff.js in node without running the main MagicMirror? It only works as a module for MagicMirror2

`Module` (capitol M) is a MagicMirror class that should always exist when running the MMM-AlexaOnOff module with MagicMirror so if you are running the core mirror code, please post the full config and console log files.

**Comment by eugenee93** [comment]
Ah Okay, I see my mistake, thanks. Tried it out with running MagicMirror2 and there was no error in the log. But somehow it still won´t turn off my monitor. 

Maybe you have an answer, Here is the full config. 
The last two rows in the console log where from my voice command, so I guess it works but don´t know why the Monitor is not responding.

** full MagicMirror config:**
```js
/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "de",
	timeFormat: 24,
	units: "metric",

	modules: [
		{
    			module: 'MMM-AlexaOnOff',
    			config: {
      		 		 devices: [{ 
             				 name: "Magic Mirror",
		
              			on: { 
                			notification: "MMM-AlexaOnOff_ACTION_RECEIVED",
                			payload: { actionName:'monitorOn' }
             				},
             			off: { 
                			notification: "MMM-AlexaOnOff_ACTION_RECEIVED",
                			payload: { actionName:'monitorOff' }
              				},
       				 }]
    			}
		},

		{
			module: "alert",
		},

		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "MMM-Fuel",
			position: "top_left",
	  	        config: {
					api_key: " //my key",
					lat: //cordinates,
					lng: //cordinates,
					types: ["e5"],
					radius: 2.5
			}		
			
		},
/*		{
*			module: "calendar",
*			header: "Kalender",
*			position: "top_left",
*	  	        config: {
*				calendars: [
*					{
*						symbol: "calendar-check-o ",
*						url: "https://calendar.google.com/calendar/ical/de.german%23holiday%40group.v.calendar.google.com/public/basic.ics"
*					}
*				]
*			}
*		},
*/
	
		{
			module: "compliments",
			position: "lower_third"
		},
		{
			module: "currentweather",
			position: "top_right",
			config: {
				location: "Aschaffenburg,DE",
				locationID: "",  //ID from http://bulk.openweathermap.org/sample/; unzip the gz file and find your city
				appid: "//my ID"
			}
		},
		{
			module: "weatherforecast",
			position: "top_right",
			header: "Wetterbereicht",
			config: {
				location: "Aschaffenburg,DE",
				locationID: "",  //ID from http://www.openweathermap.org/help/city_list.txt
				appid: "//myID"
			}
		},
		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "Nachrichten",
						url: "http://www.tagesschau.de/xml/rss2"
					}
				],
				showSourceTitle: true,
				showPublishDate: true
			}
		},
	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}
```

**full config fauxmojs:**
```js
'use strict';

const FauxMo = require('fauxmojs');

let fauxMo = new FauxMo(
  {
    ipAddress: '//myIP',
    devices: [
           {
        name: 'Magic Mirror',
        port: 11001,
        handler: (action) => {
          console.log('Magic Mirror action:', action);
        }
      }
    ]
  });

console.log('started..');
```

**console log:**
```shell
pi@raspberrypi:~/MagicMirror $ npm start

> magicmirror@2.5.0 start /home/pi/MagicMirror
> sh run-start.sh

Starting MagicMirror: v2.5.0
Loading config ...
Loading module helpers ...
Initializing new module helper ...
Module helper loaded: MMM-AlexaOnOff
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: MMM-Fuel
No helper found for module: compliments.
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: MMM-AlexaOnOff
Module helper started for MMM-AlexaOnOff
Connecting socket for: updatenotification
Connecting socket for: MMM-Fuel
Starting module helper: MMM-Fuel
Connecting socket for: newsfeed
Starting module: newsfeed
Sockets connected & modules started ...
Launching application.
FauxMo service started. Listening on _my IP Adress_:11001
Create new news fetcher for url: http://www.tagesschau.de/xml/rss2 - Interval: 300000
Fauxmo Action for Magic Mirror: off
Fauxmo Action for Magic Mirror: on
```

**Comment by shbatm** [comment]
It looks like you still need a module capable of turning on/off the monitor.  Try installing [MMM-Remote-Control](https://github.com/Jopyth/MMM-Remote-Control) by following the instructions for that module and then replace the MMM-AlexaOnOff section in your config:

```js
{
   module: 'MMM-AlexaOnOff',
   config: {
      devices: [{
         name: "Magic Mirror",
         on: {
            notification: "REMOTE_ACTION",
            payload: {
               action: 'MONITORON'
            }
         },
         off: {
            notification: "REMOTE_ACTION",
            payload: {
               action: 'MONITOROFF'
            }
         },
      }]
   }
},
{
    module: 'MMM-Remote-Control'
},
```

Also -- just, FYI, when posting more than one block of code, use 3 back-ticks (```) on the line before and after-- I edited your posts above if you click edit you'll see what I'm talking about.

**Comment by shbatm** [comment]
Also, it looks like you're new to the MagicMirror community. If so, welcome. You may want to try posting on the [forum here](https://forum.magicmirror.builders), you'll get help from more than just me on this type of stuff.

**Comment by eugenee93** [comment]
Thank you very muchfor the help and tips. Yes I am new to the community, started building my Magic Mirror a week ago.
